# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Build Methods

on:
  push:

jobs:
  build-and-test-env:
    runs-on: ubuntu-latest
    container:
      image: nclgbd/asltrain:develop
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: Build env
      run: |
        mkdir -p /workdir/media/ /workdir/incorrect_images/ /workdir/saved_models/
        # get zip file from google doc
        wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1QZj_E8ixxh4n2Bv4AcSCcFayNejeBQV0' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1QZj_E8ixxh4n2Bv4AcSCcFayNejeBQV0" -O data.zip && rm -rf /tmp/cookies.txt
        unzip -f data.zip
        rm -f data.zip

    - name: Run tests
      shell: bash -l {0}
      run: |
        bash scripts/build.sh
        mkdir -p /workdir/media/ /workdir/incorrect_images/ /workdir/saved_models/
        conda activate torch_base
        ls -la
        pytest -v -s
