# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Build Methods

on:
  push:

jobs:
  build-and-test-env:
    runs-on: ubuntu-latest
    container:
      image: nclgbd/asltrain:develop
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: Setup environment
      run: bash scripts/build.sh

    - name: Run tests
      shell: bash -l {0}
      run: |
        bash scripts/build.sh
        conda activate torch_base
        ls -la
        pytest -v -s
